package com.example.henrik_sachdeva_myruns3

import android.app.DatePickerDialog
import android.app.TimePickerDialog
import android.os.Bundle
import android.text.InputType
import android.util.Log
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.ViewModelProvider
import com.example.henrik_sachdeva_myruns3.database.ExerciseEntry
import com.example.henrik_sachdeva_myruns3.database.ExerciseEntryDatabase
import com.example.henrik_sachdeva_myruns3.database.ExerciseEntryDatabaseDao
import com.example.henrik_sachdeva_myruns3.database.ExerciseRepository
import com.example.henrik_sachdeva_myruns3.database.ExerciseViewModel
import com.example.henrik_sachdeva_myruns3.database.ExerciseViewModelFactory
import java.util.Calendar

/**
 * Activity that allows the user to manually enter exercise data.
 */
class ManualEntryActivity : AppCompatActivity() {

    private val infoItems = arrayOf(
        "Date", "Time", "Duration", "Distance", "Calories", "Heart Rate", "Comment"
    )

    private lateinit var myListView: ListView
    private lateinit var saveButton: Button
    private lateinit var cancelButton: Button
    private lateinit var viewModel: ExerciseViewModel
    private lateinit var repository: ExerciseRepository
    private lateinit var viewModelFactory: ExerciseViewModelFactory
    private lateinit var databaseDao: ExerciseEntryDatabaseDao
    private lateinit var database: ExerciseEntryDatabase

    private val selectedDateTime: Calendar = Calendar.getInstance()

    private var duration: Double? = null
    private var distance: Double? = null
    private var calories: Int? = null
    private var heartRate: Int? = null
    private var comment: String? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_manual_entry)

        myListView = findViewById(R.id.myListView)
        saveButton = findViewById(R.id.saveButton)
        cancelButton = findViewById(R.id.cancelButton)

        // Initialize Room database and ViewModel
        database = ExerciseEntryDatabase.getInstance(this)
        databaseDao = database.exerciseEntryDatabaseDao
        repository = ExerciseRepository(databaseDao)
        viewModelFactory = ExerciseViewModelFactory(repository)
        viewModel = ViewModelProvider(this, viewModelFactory)[ExerciseViewModel::class.java]

        // Set up the list with the editable fields
        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, infoItems)
        myListView.adapter = adapter

        cancelButton.setOnClickListener { finish() }

        saveButton.setOnClickListener { saveEntry() }

        myListView.setOnItemClickListener { _, _, position, _ ->
            when (position) {
                0 -> showDatePickerDialog()
                1 -> showTimePickerDialog()
                2 -> showEditNumberDialog("Duration")
                3 -> showEditNumberDialog("Distance")
                4 -> showEditNumberDialog("Calories")
                5 -> showEditNumberDialog("Heart Rate")
                6 -> showEditTextDialog("Comment")
            }
        }
    }

    /**
     * Save a new manual entry to the database.
     */
    private fun saveEntry() {
        val selectedActivityTypeId = intent.getIntExtra("SELECTED_ACTIVITY_TYPE_ID", -1)

        val newEntry = ExerciseEntry(
            id = 0L, // Auto-generated by Room
            inputType = 1,
            activityType = selectedActivityTypeId,
            dateTime = selectedDateTime,
            duration = duration ?: 0.0,
            distance = distance ?: 0.0,
            calories = calories?.toDouble() ?: 0.0,
            heartRate = heartRate?.toDouble() ?: 0.0,
            comment = comment ?: ""
        )

        try {
            viewModel.insertEntry(newEntry)
            Toast.makeText(this, "Entry saved", Toast.LENGTH_SHORT).show()
            Log.d("ManualEntryActivity", "Entry inserted into database")
        } catch (e: Exception) {
            Log.e("ManualEntryActivity", "Error saving entry: ${e.message}")
        }

        finish()
    }

    /** Opens a date picker dialog to select the date. */
    private fun showDatePickerDialog() {
        DatePickerDialog(
            this,
            { _, year, month, day ->
                selectedDateTime.set(Calendar.YEAR, year)
                selectedDateTime.set(Calendar.MONTH, month)
                selectedDateTime.set(Calendar.DAY_OF_MONTH, day)
            },
            selectedDateTime.get(Calendar.YEAR),
            selectedDateTime.get(Calendar.MONTH),
            selectedDateTime.get(Calendar.DAY_OF_MONTH)
        ).show()
    }

    /** Opens a time picker dialog to select the time. */
    private fun showTimePickerDialog() {
        TimePickerDialog(
            this,
            { _, hour, minute ->
                selectedDateTime.set(Calendar.HOUR_OF_DAY, hour)
                selectedDateTime.set(Calendar.MINUTE, minute)
            },
            selectedDateTime.get(Calendar.HOUR_OF_DAY),
            selectedDateTime.get(Calendar.MINUTE),
            false
        ).show()
    }

    /** Displays an input dialog for numeric values (e.g., duration, distance). */
    private fun showEditNumberDialog(title: String) {
        val input = EditText(this).apply {
            inputType = InputType.TYPE_CLASS_NUMBER
        }

        AlertDialog.Builder(this)
            .setTitle(title)
            .setView(input)
            .setPositiveButton("OK") { _, _ ->
                val value = input.text.toString()
                when (title) {
                    "Duration" -> duration = value.toDoubleOrNull()
                    "Distance" -> distance = value.toDoubleOrNull()
                    "Calories" -> calories = value.toIntOrNull()
                    "Heart Rate" -> heartRate = value.toIntOrNull()
                }
                Log.d("ManualEntryActivity", "Entered $title: $value")
            }
            .setNegativeButton("Cancel") { dialog, _ -> dialog.dismiss() }
            .show()
    }

    /** Displays an input dialog for text-based input (e.g., comments). */
    private fun showEditTextDialog(title: String) {
        val input = EditText(this).apply {
            hint = "How did it go? Notes here."
        }

        AlertDialog.Builder(this)
            .setTitle(title)
            .setView(input)
            .setPositiveButton("OK") { _, _ ->
                val value = input.text.toString()
                if (title == "Comment") comment = value
                Log.d("ManualEntryActivity", "Entered comment: $value")
            }
            .setNegativeButton("Cancel") { dialog, _ -> dialog.dismiss() }
            .show()
    }
}
